INSERT INTO frases(frase) VALUES ('"A consciência como estado mais elevado, virá a partir do momento em que você perceber toda atividade não consciente em si mesmo, todos aqueles aspectos que, até então,se apresentam de forma inconsciente no seu dia a dia, como condicionamentos , crenças e  padrões."');
INSERT INTO frases(frase) VALUES ('A negatividade que emitimos pode também ser definida como sofrimento. Por estarmos inconscientes, destas verdades, mantemos um estado de resistência que, por si só, já é sofrimento.');
INSERT INTO frases(frase) VALUES ('À medida que nós nos superamos natural e espontaneamente, tornamos possível a expansão de consciência para todos, pois cada um de nós é toda a humanidade.');
INSERT INTO frases(frase) VALUES ('Você deve acreditar  no "EU FAÇO" e no  "EU SOU". Eu sei que você tirará proveito do poder da mente e manifestará esse poder e ação, avançando para a auto realização.');
INSERT INTO frases(frase) VALUES ('Quando chegarmos à conclusão de que o pensamento é uma força - uma manifestação de energia - com um poder de atração semelhante a um ímã, começaremos a entender o porquê e o porquê de muitas coisas que até então nos pareciam obscuras. ');
INSERT INTO frases(frase) VALUES ('Essa questão da atração do pensamento é séria. Quando você parar para pensar, verá que um homem realmente cria seu próprio ambiente, embora culpe os outros por isso. ');
INSERT INTO frases(frase) VALUES ('Lembre-se de que você possui o poder de elevar a nota principal de sua mente a um tom positivo por um esforço da vontade é igualmente verdade que você pode se deixar levar a uma nota baixa e negativa por descuido ou vontade fraca.');
INSERT INTO frases(frase) VALUES ('A pessoa que afirma que pode e fará algo - e afirma sinceramente - desenvolve em si mesma as qualidades que a conduzirão ao seu objetivo. Ao mesmo tempo, coloca sua mente no devido lugar  para receber todas as ondas de pensamento que a ajudarão a fazer o que deseja.');
INSERT INTO frases(frase) VALUES ('Não permita que sejam afetados pelos pensamentos adversos e negativos das pessoas ao seu redor.');
INSERT INTO frases(frase) VALUES ('O desenvolvimento da vontade é muito parecido com o desenvolvimento de um músculo - uma questão de prática e melhoria gradual. A princípio, pode ser cansativo, mas a cada tentativa se torna mais forte até que a nova força se torne real e permanente. ');
INSERT INTO frases(frase) VALUES ('O meu cérebro está aprendendo a agir calma e tranquilamente para não reagir de forma instintiva aos problemas');
INSERT INTO frases(frase) VALUES ('Toda desarmonia que chega até você é uma criação sua. ');
INSERT INTO frases(frase) VALUES ('Quando você conseguir transformar cada  incômodo (sentimento) em informação, você deixará de sofrer sua própria projeção.');
INSERT INTO frases(frase) VALUES ('Sua mente não é uma usina de fabricar eventos ou benesses. As coisas devem acontecer em sua ordem natural.');
INSERT INTO frases(frase) VALUES ('Abandonar o sofrimento é tornar-se emocionalmente estável ao compreender a plenitude do Universo');
INSERT INTO frases(frase) VALUES ('A oração é a visão interior da harmonia. Esta visão é obtida pela renúncia ao desejo de mudar ou de melhorar alguém ou alguma coisa.');
INSERT INTO frases(frase) VALUES ('Os erros cometidos na prática do crescimento não interrompem o processo, mas sim o aperfeiçoa.');
INSERT INTO frases(frase) VALUES ('A liberdade é uma condição da alma. Voltando-nos para o reino do nosso Eu interior, encontramos o reino do poder divino no mundo exterior.');
INSERT INTO frases(frase) VALUES ('Quando procuramos a paz interior, encontramos harmonia fora.');
INSERT INTO frases(frase) VALUES ('Quando começamos a reconhecer nosso bem como dom da Consciência, nós deixamos o raciocínio, a especulação, o planejamento e deixamos a mente relaxar.');
INSERT INTO frases(frase) VALUES ('Aqueles que alcançaram um certo grau de consciência espiritual, comprovam a realidade do Espírito.');
INSERT INTO frases(frase) VALUES ('Tenha a certeza de que, à medida que você se voltar para a consciência espiritual, encontrará a paz, e o seu dia-a-dia se tornará mais calmo.');
INSERT INTO frases(frase) VALUES ('Todo o erro que se consumou durante os séculos baseia-se na teoria ou crença em dois mundos, (espiritual e material ) separados um do outro.');
INSERT INTO frases(frase) VALUES ('Para obtermos saúde e harmonia em nossa vida, não temos de mudar este universo material,  basta corrigirmos a visão limitada que temos da nossa existência.');
INSERT INTO frases(frase) VALUES ('Vivemos em um universo espiritual, mas a finitude de nossos sentidos desenhou para nós uma imagem de limitações.');
INSERT INTO frases(frase) VALUES ('A iluminação espiritual revela a harmonia do Ser e dispersa as aparências captadas pelos sentidos materiais. Ela nada muda no universo,  mas muda nossa visão do universo.');
INSERT INTO frases(frase) VALUES ('A iluminação espiritual pode ser alcançada por aqueles que constantemente vivenciam a consciência da presença da perfeição em tudo o que você vê.');
INSERT INTO frases(frase) VALUES ('"O pequeno ""eu"" preocupa-se basicamente com seus problemas pessoais e seus negócios, dilatando seus limites para incluir neles seus parentes próximos e seus amigos. O Eu verdadeiro corporifica as idéias e atividades infinitas, espirituais, que se manifestam continuamente, sem limites ou restrições."');
INSERT INTO frases(frase) VALUES ('Normalmente, vivemos imersos num mundo sensorial, e nos preocupamos apenas com o objeto de nossos sentidos. E isso nos traz nossa experiência de bem e de mal, de dor e de alegria.');
INSERT INTO frases(frase) VALUES ('Podemos comprovar nosso domínio sobre o tempo, o clima, a renda, a saúde e o corpo apenas na medida em que sabemos serem idéias da consciência que somos.');
INSERT INTO frases(frase) VALUES ('Nunca existe um conflito com uma pessoa ou condição, e sim com o falso conceito mentalmente mantido acerca de uma pessoa, coisa, circunstância ou condição. Por isso, faça a correção dentro de você mesmo, no lugar de tentar mudar alguém ou algo externo');
INSERT INTO frases(frase) VALUES ('Reconheça a Deus como substância, lei, causa e atividade de tudo o que é, e deixe, logo a seguir, de se imiscuir física ou psiquicamente com o mundo externo. Volte-se para dentro de si mesmo, e resolva aí todas as aparências.');
INSERT INTO frases(frase) VALUES ('Quando vivemos a partir do centro do nosso Ser, os pensamentos, as opiniões, as leis é as teorias do mundo não nos afetam. Nada nos atinge, pois nós não reagimos ao mundo das aparências.');
INSERT INTO frases(frase) VALUES ('Na vida espiritual, não colocamos rótulos sobre o mundo. Não julgamos como bom ou mau, doente ou sadio, rico ou pobre. Enquanto as aparências possam mostrar harmonia ou discórdia, pelo não julgamento, meramente reconhecemos, deixando que o que É verdadeiramente defina a si mesmo.');
INSERT INTO frases(frase) VALUES ('Viver espiritualmente é saber que tudo É; não dê nomes, rótulos, definições, nem julgue aquilo que é. Contente-se em saber que É, e deixe que aquilo que É lhe revele seu Ser, sua natureza e caráter.');
INSERT INTO frases(frase) VALUES ('Nunca busque na oração alguma coisa ou situação. Deixe que a harmonia se defina e se revele por si. Que tua oração seja um deixar o que É se revelar.');
INSERT INTO frases(frase) VALUES ('A oração é uma percepção daquilo que É, apenas "vendo-o" como é, e não fazendo-o ser.');
INSERT INTO frases(frase) VALUES ('Orar é conscientizar a harmonia sem esforço mental de nossa parte.');
INSERT INTO frases(frase) VALUES ('Orar é ausência de desejos no reconhecimento do que É.');
INSERT INTO frases(frase) VALUES ('Esteja em paz: Deus É.');
INSERT INTO frases(frase) VALUES ('Não há nenhum poder do mal externo a nós. As discórdias não têm existência externa, objetiva. Resolva isso dentro de sua própria consciência.');
INSERT INTO frases(frase) VALUES ('Há em você uma visão espiritual que tudo vê através das aparências. Esteja em paz.');
INSERT INTO frases(frase) VALUES ('A vida não está na dependência da matéria.');
INSERT INTO frases(frase) VALUES ('Quando alcançamos o centro da Consciência, encontramos uma completa tranqüilidade — uma fonte profunda do Silêncio.');
INSERT INTO frases(frase) VALUES ('Afasta-te da consciência pessoal tão rápido quanto possas. Deixe o "ego" morrer.');
INSERT INTO frases(frase) VALUES ('Toda atividade orgânica e toda função do corpo são atividades da Alma, aparecendo como ação corporal.');
INSERT INTO frases(frase) VALUES ('Toda habilidade, todo talento ou capacidade da mente são de fato ações da Alma que se faz tangível');
INSERT INTO frases(frase) VALUES ('Alcançamos a crucificação do ego quando nada resta que se possa pedir na prece.');
INSERT INTO frases(frase) VALUES ('Se algo ocorre no tempo e no espaço, não o aceite pelo valor da aparência, mas busque mais profundamente no reino da Alma.');
INSERT INTO frases(frase) VALUES ('O conhecimento do mundo espiritual muda você do plano competitivo para o plano criativo.');
INSERT INTO frases(frase) VALUES ('Antes de fazer alguma coisa você precisa ser algum coisa. Antes de ter você deve ser.');
INSERT INTO frases(frase) VALUES ('Tudo no universo é expressão de uma força infinita. Cientistas chamam isso de energia. Eu lhe digo que tudo isso é espírito. ');
INSERT INTO frases(frase) VALUES ('Pensamentos, produzem sentimentos, que provocam suas atitudes, que trazem os seus resultados.');
INSERT INTO frases(frase) VALUES ('Uma mente saturada que teme o fracasso ou a imagem de resultados indesejáveis, não pode realizar, criar ou produzir nada de valor.');
INSERT INTO frases(frase) VALUES ('Coisas estranhas e maravilhiosas vão começar aacontecer com certa regularidade e você não saberá explicar porquê e nem poderá entender. Nem tente.');
INSERT INTO frases(frase) VALUES ('O espírito (consciência)  é a verdaderia essência de você mesmo e ele nunca tomará forma sem a sua colaboração.');
INSERT INTO frases(frase) VALUES ('De tempos em tempos pode ser que nem tudo esteja indo bemn e você começará a se  preocupar. Apenas mantenha firme e clara a sua imagem do propósito.');
INSERT INTO frases(frase) VALUES ('Dúvidas, medo,  pessimismo e sentimentos negativos  envenenam a verdadeira fonta da vida.');
INSERT INTO frases(frase) VALUES ('O desejo é o motor que te move me diração ao seu sonho. A expectativa saudável é a força de tração que traz o seu sonho até você.');
INSERT INTO frases(frase) VALUES ('É praticamente impossível manter na mente uma ideia sem que essa ideia se expresse no seu mundo físico. Você é o que você pensa o dia todo.');
INSERT INTO frases(frase) VALUES ('Esteja muito consciente da direção que a sua mente está tomando, pois esta será também a direção que a sua vida tomará. ');
INSERT INTO frases(frase) VALUES ('Com conhecimento e a prática da lei espiritual, colocamo-nos em harmonia com a natureza e criamos sem ansiedade, com alegria e amor.');
INSERT INTO frases(frase) VALUES ('É preciso que se aborde o sucesso e a abundância espiritualmente, como o constante fluxo de todas as coisas boas na sua direção');
INSERT INTO frases(frase) VALUES ('O sucesso é a jornada, não o destino.');
INSERT INTO frases(frase) VALUES ('Somos uma divindade disfarçada, somos embriões de deuses e deusas que, contidos em nosso ser, buscam a plena materialização.');
INSERT INTO frases(frase) VALUES ('Lei da criação é o processo pelo qual o não manifesto torna-se manifesto.');
INSERT INTO frases(frase) VALUES ('O universo físico nada mais é que o Eu desdobrando-se como espírito, mente, matéria.');
INSERT INTO frases(frase) VALUES ('A fonte de toda criação é a divindade (o espírito). O processo da criação é o espírito em movimento (a mente).');
INSERT INTO frases(frase) VALUES ('Os três componentes da realidade - espírito, mente e corpo (observador, ato de observar e observado) - são, essencialmente, a mesma coisa.');
INSERT INTO frases(frase) VALUES ('Quando você descobre sua natureza essencial, quando sabe quem realmente é, encontra toda a sua potencialidade.');
INSERT INTO frases(frase) VALUES ('É no conhecer-se que reside a capacidade de realização de todos os sonhos, porque você mesmo representa toda a possibilidade de tudo o que foi e poderá vir a ser.');
INSERT INTO frases(frase) VALUES ('Na experiência do Eu, chamada auto-referência, nosso ponto de referência interior é o espírito e não aquilo que nos rodeia.');
INSERT INTO frases(frase) VALUES ('Quando você vive pelo ego você se  deixa influenciar pelo que acontece fora da sua natureza interior: pelas situações, circunstâncias, pessoas, coisas.');
INSERT INTO frases(frase) VALUES ('Todas as situações como:  necessidade de aprovação, de poder externo, de controle das coisas - estão baseadas no medo.');
INSERT INTO frases(frase) VALUES ('O ego reflete apenas a sua auto  imagem, a sua máscara social, o papel que você representa para os outros.');
INSERT INTO frases(frase) VALUES ('Seu auto poder magnetiza as pessoas, as situações e as circunstâncias que alimentam seus sonhos, apoiando-se nas leis naturais');
INSERT INTO frases(frase) VALUES ('Uma forma de elevar a sua consciência  é se entregar diariamente a momentos de silêncio, praticar a meditação, evitar julgamentos.');
INSERT INTO frases(frase) VALUES ('Praticar o silêncio significa assumir o compromisso de reservar uma certa quantidade de tempo para simplesmente ser.');
INSERT INTO frases(frase) VALUES ('Se você nunca se entregar à experiência do silêncio, estará provocando turbulência em seu diálogo interior.');
INSERT INTO frases(frase) VALUES ('A quietude é o primeiro requisito para que seus desejos se manifestem.');
INSERT INTO frases(frase) VALUES ('Julgar é estar constantemente avaliando as coisas como certas ou erradas, boas ou más. Se você está constantemente avaliando, classificando, rotulando, isso cria muita turbulência em seu diálogo interior.');
INSERT INTO frases(frase) VALUES ('É no estado de percepção pura, nesse espaço silencioso e calmo entre os pensamentos,  que você entra em contato com o poder verdadeiro.');
INSERT INTO frases(frase) VALUES ('Você precisa aprender a entrar em contato com a mais profunda essência de seu ser. Ela está além do ego, é isenta de medo, livre, imune à critica, não teme nenhum desafio.');
INSERT INTO frases(frase) VALUES ('Nenhuma quantia de dinheiro ou sucesso resolverá esses problemas básicos da sua vida. Somente a intimidade com seu verdadeiro Eu permitirá superar tais problemas.');
INSERT INTO frases(frase) VALUES ('Quanto mais você acessa a sua verdadeira natureza, mais espontaneamente aparecem os pensamentos criativos.');
INSERT INTO frases(frase) VALUES ('Aprenda a ficar quieto, silencioso e solitário. O mundo se oferecerá espontaneamente a você para ser descoberto.');
INSERT INTO frases(frase) VALUES ('A maneira mais fácil de obter o que se quer é ajudar os outros a conseguir o que querem.');
INSERT INTO frases(frase) VALUES ('Toda ação gera uma força energética que retorna a nós da mesma forma... O que semeamos é o que colhemos.');
INSERT INTO frases(frase) VALUES ('Quer você goste ou não, tudo o que está acontecendo neste momento é resultado de escolhas feitas no passado.');
INSERT INTO frases(frase) VALUES ('Toda pessoa constitui um feixe de reflexos condicionados. Eles são disparados, constantemente, por circunstâncias e por pessoas, resultando em comportamentos previsíveis.');
INSERT INTO frases(frase) VALUES ('Suas reações não podem ser disparadas automaticamente por pessoas e por circunstâncias. Você tem que estar consciente o tempo todo.');
INSERT INTO frases(frase) VALUES ('Se você parar um pouco e começar a observar suas escolhas no momento em que elas ocorrem,  mudará qualquer  aspecto de inconsciência');
INSERT INTO frases(frase) VALUES ('O simples ato de se auto observar  transfere todo o processo do terreno do inconsciente para o terreno do consciente.');
INSERT INTO frases(frase) VALUES ('Quando você  escolhas conscientes   elas resultam numa forma de comportamento chamada de ação correta espontânea.');
INSERT INTO frases(frase) VALUES ('Somente o coração conhece a resposta certa e ele trabalha por intuição.');
INSERT INTO frases(frase) VALUES ('Nada do que se deve ao universo fica sem pagar, mas você pode tornar isso um aprendizado interessante. Pergunte-se: o que estou aprendendo com esta experiência?');
INSERT INTO frases(frase) VALUES ('se transformar em um escolhedor consciente, você passa a gerar ações transformadoras para si e para os que estão ao seu redor.');
INSERT INTO frases(frase) VALUES ('A inteligência da natureza funciona com tranqüila facilidade e sem nenhuma ansiedade.');
INSERT INTO frases(frase) VALUES ('A terra não se esforça para girar sobre seu eixo. E é da natureza humana materializar seus sonhos, facilmente, sem nenhum esforço.');
INSERT INTO frases(frase) VALUES ('O que é comumente chamado de "milagre" é, na verdade, uma expressão da lei do mínimo esforço.');
INSERT INTO frases(frase) VALUES ('Quando você busca o poder e o controle sobre as pessoas, está desperdiçando energia.');
INSERT INTO frases(frase) VALUES ('Quando busca dinheiro somente para uso próprio, interrompe o fluxo de energia em direção a si mesmo e interfere na manifestação da inteligência da natureza.');
INSERT INTO frases(frase) VALUES ('Você pode imaginar seu corpo como um mecanismo controlador de energia.');
INSERT INTO frases(frase) VALUES ('Se o seu ponto de referência interno for o ego e você buscar controlar sobre outras pessoas, ou buscar a aprovação dos outros, você vai desperdiçar muita energia.');
INSERT INTO frases(frase) VALUES ('Desenvolva a atitude de aceitar pessoas, situações, circunstâncias e fatos, da maneira como eles se apresentam.');
INSERT INTO frases(frase) VALUES ('Quando você luta contra o momento em que está vivendo, você está lutando contra todo o universo.');
INSERT INTO frases(frase) VALUES ('Aceite as coisas como elas são e não como você gostaria que elas  fossem. Isso não  é ser conformado. É ter um propósito e saber esperar por ele.');
INSERT INTO frases(frase) VALUES ('Quando você estiver decepcionado ou aborrecido com uma pessoa ou com uma situação, lembre-se de que não está reagindo à pessoa ou à situação, mas sim aos seus sentimentos pela pessoa ou situação.');
INSERT INTO frases(frase) VALUES ('Os sentimentos são seus e o que você está sentindo agora não é culpa de mais ninguém.');
INSERT INTO frases(frase) VALUES ('Responsabilidade é não ficar culpando alguém, ou alguma coisa pela situação, muito menos a si mesmo');
INSERT INTO frases(frase) VALUES ('Aceitando a circunstância, ou problema como se apresenta no momento, a responsabilidade passa a ser a capacidade de ter uma resposta criativa para aquela situação.');
INSERT INTO frases(frase) VALUES ('Todos os problemas contêm em si as sementes da oportunidade.');
INSERT INTO frases(frase) VALUES ('A realidade é uma interpretação. Se você escolher interpretar a realidade sem julgamentos, você terá muitas oportunidades para evoluir.');
INSERT INTO frases(frase) VALUES ('Desarme seu espírito e abra mão da necessidade de convencer e persuadir os outros de seus pontos de vista.');
INSERT INTO frases(frase) VALUES ('Toda vez que encontrar resistência, se tentar forçar a situação, a resistência só aumentará.');
INSERT INTO frases(frase) VALUES ('Quando você começar a experimentar a exultação do espírito em todas as coisas vivas, sentirá o despertar de uma grande alegria interior e abandonará os terríveis fardos do ressentimento e do sofrimento.');
INSERT INTO frases(frase) VALUES ('Seus desejos devem surgir da felicidade e não da ansiedade, ou do medo.');
INSERT INTO frases(frase) VALUES ('Assuma o compromisso de seguir o caminho da não resistência. É o caminho no qual a inteligência da natureza se abre espontaneamente, sem atrito, sem esforço.');
INSERT INTO frases(frase) VALUES ('Se você permanecer aberto a todos os pontos de vista - sem se prender rigidamente a nenhum deles - seus sonhos e desejos fluirão com os desejos da natureza.');
INSERT INTO frases(frase) VALUES ('Todo o universo, em sua natureza essencial, é movimento da energia e da informação. Seu sentimento é energia e informação.');
INSERT INTO frases(frase) VALUES ('Quanto mais tranquila uma pessoa se torna, maior é o seu sucesso, a sua influência, o seu poder para o bem.');
INSERT INTO frases(frase) VALUES ('Você  é feito ou desfeito por si próprio; no arsenal do seu pensamento, você  forja as armas com as quais se destrói ou constrói a si mesmo.');
INSERT INTO frases(frase) VALUES ('Todo pensamento emocionalizado, reforçado pelo sentimento, transforma-se em realidade física.');
INSERT INTO frases(frase) VALUES ('O pensamento (com sentimento)  é uma realidade mental que atrai a realidade física. pensamentos de fracasso atraem o fracasso, pensamentos de sucesso atraem o sucesso. ');
INSERT INTO frases(frase) VALUES ('Seu futuro será a colheita dos pensamentos semeados na sua mente hoje.');
INSERT INTO frases(frase) VALUES ('O bem e o mal não existem, o pensamento é que os cria.');
INSERT INTO frases(frase) VALUES ('O mundo exterior de circunstância molda-se ao mundo interior do pensamento.');
INSERT INTO frases(frase) VALUES ('Você não atrai aquilo que você quer, mas aquilo que você é.');
INSERT INTO frases(frase) VALUES ('Você pode estar continuamente a revoltar-se contra um efeito, enquanto está o tempo todo a alimentar e a preservar no seu coração, a causa.');
INSERT INTO frases(frase) VALUES ('As pessoas estão ansiosas por melhorarem as suas circunstâncias, mas não estão dispostas a melhorarem-se a elas mesmas, logo mantém-se presas.');
INSERT INTO frases(frase) VALUES ('Maus pensamentos eações nunca podem produzir bons resultados. As pessoas compreendem esta lei no mundo natural e trabalham com ela; mas poucos a compreendem no mundo mental.');
INSERT INTO frases(frase) VALUES ('O sofrimento é sempre o efeito de pensamento errado numa qualquer direcção. É uma indicação de que o indivíduo está em desarmonia consigo com aLei do seu ser.');
INSERT INTO frases(frase) VALUES ('O uso único e supremo do sofrimento é purificar, queimar tudo que é inútil e impuro. O sofrimento cessa para uma pessoa que é pura.');
INSERT INTO frases(frase) VALUES ('As circunstâncias em que uma pessoa enfrenta sofrimento são resultado da sua própria desarmonia mental.');
INSERT INTO frases(frase) VALUES ('Pobreza e vitimismo são os dois extremos da desgraça. Ambos são resultado de uma desordem mental. Pobreza é diferente de poucos recursos. Riqueza é um ajustamento da pessoa com o seu ambiente.');
INSERT INTO frases(frase) VALUES ('Enquanto o seu pensamento não for igual ao seu propósito nunca haverá realização inteligente.');
INSERT INTO frases(frase) VALUES ('Quem não tem um propósito central nas sua vida é presa fácil de preocupações, medos, problemas e autocomiserações insignificantes.');
INSERT INTO frases(frase) VALUES ('Você pode imaginar seu corpo como um mecanismo controlador de energia. Ele pode gerar, armazenar e utilizar energia. Se você sabe como gerar, armazenar e utilizar energia de maneira eficiente, poderá criar riquezas em quantidade');
INSERT INTO frases(frase) VALUES ('Seu corpo não está separado de corpo do universo. O grande campo quântico - o universo - é o seu corpo estendido.');
INSERT INTO frases(frase) VALUES ('Quando você concentra sua atenção em alguma coisa, ela fica mais forte em sua vida. Quando você afasta a atenção de alguma coisa, ela enfraquece, desintegra e desaparece.');
INSERT INTO frases(frase) VALUES ('O passado representa as recordações, a memória. O futuro é antecipação. O presente é consciência. Portanto, o tempo é o movimento do pensamento.');
INSERT INTO frases(frase) VALUES ('Tanto passado quanto futuro são frutos da imaginação. Somente o presente é consciência, é real, é eterno.');
INSERT INTO frases(frase) VALUES ('Se você tiver consciência do momento presente centrado na vida, os obstáculos imaginários - que são mais de noventa por cento dos obstáculos percebidos  desintegram-se e desaparecem.');
INSERT INTO frases(frase) VALUES ('Desfrute todos os momentos da jornada de sua vida, mesmo sem saber quais serão os resultados. Viva a sabedoria da incerteza.');
INSERT INTO frases(frase) VALUES ('Se as coisas não saírem como você desejou há uma razão para isso. O plano cósmico com certeza terá desígnios maiores para você do que os que você possa conceber.');
INSERT INTO frases(frase) VALUES ('A ansiedade é baseada no medo e na insegurança. A necessidade de segurança está fundamentada no desconhecimento do verdadeiro Eu.');
INSERT INTO frases(frase) VALUES ('O apego vem da pobreza de consciência, porque o apego é sempre por símbolos. Os símbolos (casa, carro, dinheiro)  são transitórios; eles vêm e vão. Perseguir símbolosao invés do seu "EU" cria ansiedade e acaba levando você a se sentir vazio.');
INSERT INTO frases(frase) VALUES ('A verdadeira consciência é a habilidade de ter tudo o que se quer, na hora que se quer, com o mínimo esforço. Para viver esta experiência você tem de estar apoiado na sabedoria da incerteza.');
INSERT INTO frases(frase) VALUES ('Não é preciso ter uma idéia pronta e acabada do que você vai estar fazendo nas próximas semanas, ou no ano que vem, porque se você já sabe o que vai acontecer e se apega a essa idéia, abre mão de toda a gama de possibilidades.');
INSERT INTO frases(frase) VALUES ('Se você forçar a solução de problemas, só vai criar mais problemas. ');
INSERT INTO frases(frase) VALUES ('Quando você  dirige sua atenção para a incerteza e observa essa incerteza enquanto espera a solução emergir do caos e da confusão, o que aparecerá  será fabuloso e excitante.');
INSERT INTO frases(frase) VALUES ('Em cada um dos problemas está a oportunidade de um benefício maior.');
INSERT INTO frases(frase) VALUES ('Você tem um propósito de vida...um dom singular ou um talento único para dar aos outros.');
INSERT INTO frases(frase) VALUES ('Existe alguma coisa que você consegue fazer melhor do que todo mundo.');
INSERT INTO frases(frase) VALUES ('Quando as  necessidades das pessoas se combinam com a expressão criativa de seu talento, surge a fagulha que cria a riqueza.');
INSERT INTO frases(frase) VALUES ('Há uma razão para você estar aqui e cada um tem que descobrir por si mesmo que razão era essa.');
INSERT INTO frases(frase) VALUES ('Nosso verdadeiro Eu é espiritual e somos essencialmente seres espirituais expressos numa forma física.');
INSERT INTO frases(frase) VALUES ('Pergunte-se sempre: como posso ajudar?", em vez de "o que vou ganhar com isso?"');
INSERT INTO frases(frase) VALUES ('Quando sua expressão criativa combina-se às necessidades de seus semelhantes, a riqueza flui espontaneamente do não manifesto para o manifesto, do reino do espírito para o mundo da forma física.');
INSERT INTO frases(frase) VALUES ('O segredo de uma vida harmoniosa é o desenvolvimento da consciência espiritual');
INSERT INTO frases(frase) VALUES ('O Infinito Invisível (consciência/Deus) aperfeiçoará tudo que nos for dado para fazer no mundo visível.');
INSERT INTO frases(frase) VALUES ('Gradualmente, quando mais e mais a tentação vem para nos dizer: “Eu necessito; Eu quero; Eu não tenho o suficiente; recordamo-nos que nossa suficiência está no Infinito Invisível.');
INSERT INTO frases(frase) VALUES ('Todo assunto da vida é determinado, não pelas condições e coisas aparentes, mas por nossa consciência.');
INSERT INTO frases(frase) VALUES ('Quando a consciência se torna mais espiritual, a confiança no Infinito Invisível aumenta, e o medo da aparência diminui. ');
INSERT INTO frases(frase) VALUES ('Comece a sua vida espiritual por compreender que todos os conflitos devem ser apaziguados dentro da sua consciência.');
INSERT INTO frases(frase) VALUES ('Quando vivemos a partir do centro do nosso Ser, os pensamentos, as opiniões, as leis é as teorias do mundo não nos afetam. Nada nos atinge, pois nós não reagimos ao mundo das aparências.');
INSERT INTO frases(frase) VALUES ('Nunca busque na oração alguma coisa ou situação. Deixe que a harmonia se defina e se revele por si. Que tua oração seja um deixar o que É se revelar.');
INSERT INTO frases(frase) VALUES ('A oração é uma percepção daquilo que É, apenas "vendo-o" como é, e não fazendo-o ser.');
INSERT INTO frases(frase) VALUES ('Não há nenhum poder do mal externo a nós. As discórdias não têm existência externa, objetiva. Resolva isso dentro de sua própria consciência.');
INSERT INTO frases(frase) VALUES ('Todo pensamento emocionalizado, unido à fé, tende a se realizar, a se materializar.');
INSERT INTO frases(frase) VALUES ('Nossa força maior não está na capacidade de pensar, mas em algo mais poderoso: o poder de controlar e direcionar nossos pensamentos para onde quisermos.');
INSERT INTO frases(frase) VALUES ('É impossível para um homem ser enganado por outra pessoa que não seja ele próprio.');
INSERT INTO frases(frase) VALUES ('Não aprendeu a lição da vida quem não domina o medo de cada dia.');
INSERT INTO frases(frase) VALUES ('Os impulsos de energia e informação (pensamento e sentimento ) que criam nossas experiências refletem-se em nossas atitudes diante da vida, e nossas atitudes são o resultado e a expressão dos impulsos que nós mesmos geramos. ');
INSERT INTO frases(frase) VALUES ('O desprendimento leva automaticamente à caridade e à partilha, pois ele derivada consciência de que a fonte que dá origem a tudo é infinita, ilimitada e inesgotável.');
INSERT INTO frases(frase) VALUES ('Quando você abandonar a necessidade de estar sempre classificando as coisas como boas ou más, certas ou erradas, sentirá um silêncio maior em sua consciência. ');
INSERT INTO frases(frase) VALUES ('O corpo é um campo de moléculas. A mente é um campo de idéias. Aonde quer que vá um pensamento, uma molécula vai atrás.');
INSERT INTO frases(frase) VALUES ('Ninguém está errado. Aos olhos do amor, todas as pessoas estão fazendo o melhor que podem segundo seus níveis de consciência.');
INSERT INTO frases(frase) VALUES ('As outras pessoas parecem erradas quando as perspectivas delas não correspondem as suas. Todos os desacordos são resultados da má compreensão do nível de consciência de outra pessoa.');
INSERT INTO frases(frase) VALUES ('A experiência da liberdade e da unidade somente é possível quando você pode realmente seguir o seu coração.');
INSERT INTO frases(frase) VALUES ('A essência do ser humano é o amor. Mas, por conta dos choques de abandono, exclusão, humilhação e rejeição, nos esquecemos de amar e aprendemos a odiar.');
INSERT INTO frases(frase) VALUES ('O ego é uma falsa ideia sobre quem você realmente é.');
INSERT INTO frases(frase) VALUES ('Tenha sempre em mente que, quanto maior a agressividade, a arrogância, ou qualquer outro mecanismo de defesa, maior é a dor e o vazio que você sentirá.');
INSERT INTO frases(frase) VALUES ('Lá fora o mundo vai continuar te convidando para a briga. A questão é se você aceita esse convite ou não.');
INSERT INTO frases(frase) VALUES ('A crença de que a felicidade depende do outro ou de certas situaçõses manifesta todos os seus probelmas que você sofre hoje.');
INSERT INTO frases(frase) VALUES ('O que ocorre na sua vida é um reflexo daquilo que você é. Nós somos cocriadores da realidade.');
INSERT INTO frases(frase) VALUES ('Tendemos a prestar mais atenção nos defeitos e a olhar primeiramente para aquilo que está faltando, não para o que já conquistamos. ');
INSERT INTO frases(frase) VALUES ('Um importante ponto a ser compreendido é que não há separação entre o que ocorre dentro e o que ocorre fora de nós – o externo é reflexo do interno.');
INSERT INTO frases(frase) VALUES ('Você não é impulsionado pela realidade, mas sim por sua percepção da realidade.');
INSERT INTO frases(frase) VALUES ('Se insistir em focalizar o que você não quer, mais disso você terá!');
INSERT INTO frases(frase) VALUES ('Qualquer padrão de emoção ou comportamento que seja reforçado de um modo contínuo se tornará uma reação automática e condicionada. Qualquer coisa que você deixar de reforçar acabará por se dissipar.');
INSERT INTO frases(frase) VALUES ('Assim que você verdadeiramente se empenhar para que aconteça alguma coisa, o "como" vai aflorar por si mesmo.');
INSERT INTO frases(frase) VALUES ('A vida não passa de um jogo em que todas as respostas existem; você só precisa encontrar as perguntas certas para vencer.');
INSERT INTO frases(frase) VALUES ('Se você não dirige seus  pensamentos, cairá sob a influência daqueles que te condicionam para que você comporte como eles desejam.');
INSERT INTO frases(frase) VALUES ('A dor é o supremo instrumento para alterar uma convicção.');
INSERT INTO frases(frase) VALUES ('Você nem faz ideia da capacidade que você  consegue reunir quando concentra todos os seus  recursos no domínio de uma única área de sua vida.');
INSERT INTO frases(frase) VALUES ('Sempre que seu sentimento está em conflito com seu desejo, o sentimento será o vitorioso.');
INSERT INTO frases(frase) VALUES ('Uma mudança de sentimento é uma mudança de destino.');
INSERT INTO frases(frase) VALUES ('A vida não comete erros, e sempre dá ao homem aquilo que o homem se dá primeiro.');
INSERT INTO frases(frase) VALUES ('Saúde, riqueza, beleza e genialidade não são criados; eles só são manifestados pelo pensamento de sua mente que é, pelo seu conceito de si mesmo [e seu conceito de si mesmo é tudo o que você aceita e concorda como a verdade.');
INSERT INTO frases(frase) VALUES ('Tudo o que acontece com você  acontece como resultado de seu estado de consciência.');
INSERT INTO frases(frase) VALUES ('Transformai-vos pela renovação da sua mente. [Romanos 12:2]');
INSERT INTO frases(frase) VALUES ('Sentimento é o primeiro e único meio através do qual ideias são transmitidas ao subconsciente e são materializadas. Portanto, se você que não controla seus sentimentos pode facilmente imprimir no subconsciente estados indesejáveis. ');
INSERT INTO frases(frase) VALUES ('Você não consegue controlar os sentimentos, mas consegue  disciplinar-se a imaginar e abrigar apenas tais sentimentos que contribuam para a sua felicidade. ');
INSERT INTO frases(frase) VALUES ('Não se concentre em suas imperfeições ou as dos outros. Assim fazendo você imprime o subconsciente com essas limitações. ');
INSERT INTO frases(frase) VALUES ('Cada sentimento faz uma impressão subconsciente que deverá ser expressa no mundo físico, a menos que ele seja compensado por um forte sentimento de natureza oposta. ');
INSERT INTO frases(frase) VALUES ('O que você sente que é sempre domina sobre o que você sente que gostaria de ser;');
INSERT INTO frases(frase) VALUES ('Tenha cuidado de seus estados de humor e sentimentos, porque há uma conexão inquebrável entre seus sentimentos e seu mundo visível. ');
INSERT INTO frases(frase) VALUES ('Seu corpo é um filtro emocional e apoia as marcas inconfundíveis de suas emoções dominantes.');
INSERT INTO frases(frase) VALUES ('Os distúrbios emocionais, especialmente as emoções reprimidas, são a causa de todas as doenças. ');
INSERT INTO frases(frase) VALUES ('Sentir intensamente sobre algo errado, sem verbalizar ou expressar esse sentimento, é o início de doenças no corpo e no ambiente. ');
INSERT INTO frases(frase) VALUES ('Não abrigue o sentimento de remorso ou fracasso porque a frustração ou desprendimento de seu objetivo resulta na doença.');
INSERT INTO frases(frase) VALUES ('Toda a criação ocorre no domínio do subconsciente. O que você deve adquirir, então, é um controle reflexo do funcionamento do subconsciente, ou seja, a disciplina de seus pensamentos e sentimentos. Transforme cada sentimento em informação e aprenda com ele.');
INSERT INTO frases(frase) VALUES ('O subconsciente não está preocupado com a verdade ou a falsidade de seu sentimento. Sempre aceita como verdade o que você sente como verdadeiro. ');
INSERT INTO frases(frase) VALUES ('O sentimento é o consentimento do subconsciente da verdade do que é declarado verdadeiro.');
INSERT INTO frases(frase) VALUES ('Seus sentimentos criam o padrão desde o qual seu mundo é criado e uma mudança no sentimento é uma mudança de padrão. ');
INSERT INTO frases(frase) VALUES ('O subconsciente nunca modifica as crenças que o homem aceita. Ela as EXPRESSA até seus últimos detalhes sejam elas benéficas ou não.');
INSERT INTO frases(frase) VALUES ('Se você se concentra mais do que qualquer coisa nas dificuldades, barreiras ou atrasos, o subconsciente pela sua natureza não seletiva, aceita o sentimento de dificuldades e obstáculos como sua solicitação e prossegue para produzi-los em seu mundo exterior.');
INSERT INTO frases(frase) VALUES ('Sentir desespero ou impossibilidade é imprimir ao subconsciente com a ideia de fracassar. ');
INSERT INTO frases(frase) VALUES ('O que está dentro é como o que está fora”. “Um homem não pode receber nada a menos que lhe seja dado do céu”. E “o Reino dos céus está dentro de você.');
INSERT INTO frases(frase) VALUES ('Nada vem de fora; todas as coisas vêm de dentro - do subconsciente.  É impossível para você ver outra coisa senão o conteúdo de sua consciência.');
INSERT INTO frases(frase) VALUES ('Buscar no exterior por aquilo que você não sente que é, é buscar em vão, porque nunca encontramos o que desejamos; encontramos apenas o que somos.');
INSERT INTO frases(frase) VALUES ('O domínio do autocontrole dos seus pensamentos e sentimentos é a maior realização.');
INSERT INTO frases(frase) VALUES ('O mundo não pode mudar a menos que você mude sua concepção dele. “Como é dentro é fora”');
INSERT INTO frases(frase) VALUES ('As nações, bem como as pessoas são apenas o que você acha que elas são.');
INSERT INTO frases(frase) VALUES ('Uma mudança de crença é confirmada através de uma mudança de expressão. Quando você  muda as causas, mudam-se os efeitos.');
INSERT INTO frases(frase) VALUES ('Ideias envolvidas em sentimentos são ações criativas. Use seu direito divino sabiamente. Através de sua capacidade de pensar e sentir você tem o domínio de toda a criação. ');
INSERT INTO frases(frase) VALUES ('Assim  na terra como no céu. Assim é na expressão física como o é na consciência.');
INSERT INTO frases(frase) VALUES ('A oração é uma ilusão de estado que diminui a impressão do mundo exterior e coloca a mente mais receptiva à sugestão que vem de  dentro.');
INSERT INTO frases(frase) VALUES ('Quando você está no estado mental, “eu gostaria, mas não posso” você jamais conseguirá  obter aquilo que deseja. Você nunca atrai aquilo que quer, mas sempre atrai aquilo que está consciente de ser.');
INSERT INTO frases(frase) VALUES ('Há um sentimento definido associado com cada ideia na mente do homem.');
INSERT INTO frases(frase) VALUES ('Àquele que tem lhe será dado, e terá em abundância; mas ao que não tem, até aquilo que tem ser-lhe-á tirado” O que você sente que é, você é e lhe darão aquilo que é.');
INSERT INTO frases(frase) VALUES ('Onde você vive psicologicamente, determina a forma como você vive mundo visível externo.');
INSERT INTO frases(frase) VALUES ('Para ser transformado, toda a base de seus pensamentos devem mudar. Mas seus pensamentos não podem mudar a menos que você tenha novas ideias, para pensar a partir delas.');
INSERT INTO frases(frase) VALUES ('As mudanças que ocorrem em sua vida são resultadas das mudanças do conceito de si mesmo, para os leigos parece ser o resultado, não de uma mudança de consciência, mas da mudança de causas externas ou coincidência.');
INSERT INTO frases(frase) VALUES ('O único destino que rege sua vida é o destino determinado por seus próprios conceitos, suas próprias suposições. Uma suposição, embora falsa, se você persistir nela, elas se tornará uma realidade fixa.');
INSERT INTO frases(frase) VALUES ('Não há escapatória para você, exceto por uma transformação psicológica radical de si mesmo.');
INSERT INTO frases(frase) VALUES ('Toda transformação é baseada em sugestão, e isto pode trabalhar apenas onde você se põe completamente aberto a uma influência.');
INSERT INTO frases(frase) VALUES ('Desde que a sua vida é determinada por seus pensamentos e sentimentos, você é forçado a reconhecer o fato de que você é ou um escravo de suas escolhas  ou seu mestre delas.');
INSERT INTO frases(frase) VALUES ('Você pode alcançar domínio de sua mente pelo controle consciente deliberado de sua imaginação.');
INSERT INTO frases(frase) VALUES ('Cada estado ou condição já está lá como "meras possibilidades", enquanto nós pensamos neles, mas como poder real quando pensamos a partir deles.');
INSERT INTO frases(frase) VALUES ('Quando você entende a função redentora da imaginação, você tem em suas mãos a chave para a solução de todos os seus problemas.');
INSERT INTO frases(frase) VALUES ('Você está limitado apenas pela sua imaginação descontrolada e falta de atenção para com os seus  sentimentos.');
INSERT INTO frases(frase) VALUES ('Você deve parar de gastar seus pensamentos, seu tempo e seu Dinheiro. Tudo na vida deve ser um investimento.');
INSERT INTO frases(frase) VALUES ('Alguém que tem a mente dividida e é instável em todos os seus caminhos. [Tiago 1:8]');
INSERT INTO frases(frase) VALUES ('A atitude atenta envolve a seleção, pois quando você prestar atenção, isso significa que você decidiu concentrar sua atenção em um objeto ou estado, em vez de focar em outra coisa.');
INSERT INTO frases(frase) VALUES ('As ideias que impelem à ação são aquelas que dominam a consciência e recebem a sua atenção.');
INSERT INTO frases(frase) VALUES ('Se o seu conceito de si mesmo é que você é um fracasso, você irá encontrar  toda uma série de incidentes em conformidade com esse conceito.');
INSERT INTO frases(frase) VALUES ('Você é livre para escolher o conceito que você vai aceitar de si mesmo. Portanto, você possui o poder de intervenção, o poder que lhe permite alterar o curso do seu futuro.');
INSERT INTO frases(frase) VALUES ('Quando você é capaz de controlar os movimentos de sua atenção no mundo subjetivo, você pode modificar ou alterar a sua vida como quiser.');
INSERT INTO frases(frase) VALUES ('Sempre que você se torna completamente absorvido em um estado emocional, você está naquele momento assumindo a realidade desse estado.');
INSERT INTO frases(frase) VALUES ('Tudo está consumado. Tudo o que você deseja já existe, mas tudo isso é  excluído de sua  vista, porque você pode ver apenas o conteúdo da sua própria consciência.');
INSERT INTO frases(frase) VALUES ('Para o Senhor (consciência)  não vê como vê o homem, pois o homem olha para o exterior, porém o Senhor (consicência)  olha para o coração. 1Samuel 16:7');
INSERT INTO frases(frase) VALUES ('Buscai primeiro o reino de Deus e a sua justiça, e todas estas coisas vos serão acrescentadas você. Mateus 6:33 O reino (criação inteira) de Deus (seu EU SOU) está dentro de você. A justiça é a consciência de que você possui tudo isso.');
INSERT INTO frases(frase) VALUES ('Tenha em mente é que você tem infinito livre arbítrio na escolha de seus pensamentos, mas não tem poder para determinar as condições e eventos. Você não pode criar nada, mas suas escolhas mentais determinam que parte da criação que você vai experimentar.');
INSERT INTO frases(frase) VALUES ('Quando entendemos que a consciência é a única realidade, sabemos que ela é o único criador. Isto significa que a sua consciência é o criador de seu destino.');
INSERT INTO frases(frase) VALUES ('O fato é que você está criando o seu destino a cada momento, você sabendo disso ou não.');
INSERT INTO frases(frase) VALUES ('Muito do que é bom e até mesmo maravilhoso entrou em sua vida sem você  ter qualquer ideia de que você era o criador de tudo.');
INSERT INTO frases(frase) VALUES ('Defina o que você quer da vida e siga por essa estrada. Você chega lá com absoluta certeza. A mente subconsciente responde de forma infalível ao que for programado.');
INSERT INTO frases(frase) VALUES ('Você tem a idade dos seus pensamentos.');
INSERT INTO frases(frase) VALUES ('Tudo o que uma pessoa realiza e tudo o que uma pessoa falha em realizar é o resultado directo dos seus próprios pensamentos.');
INSERT INTO frases(frase) VALUES ('Uma pessoa que viva constantemente na concepção de pensamentos nobres e sublimes alcançará uma posição de influência e felicidade.');
INSERT INTO frases(frase) VALUES ('A Visão que você glorifica na sua mente, o Ideal que você exalta no seu coração... é sobre isto que você constrói a sua vida, é nisto que você se vai tornar.');
INSERT INTO frases(frase) VALUES ('A tranquilidade da mente é uma das bonitas jóias da sabedoria. É o resultado de um esforço longo e paciente do autocontrole.');
INSERT INTO frases(frase) VALUES ('Uma pessoa torna-se calma à medida que se compreende a si própria como um ser que deriva do pensamento.');
INSERT INTO frases(frase) VALUES ('O auto observador desenvolve uma compreensão correcta, e vê mais e mais claramente as relações internas das coisas pela ação da causa e efeito.');
INSERT INTO frases(frase) VALUES ('O auto observador cessa de fazer espalhafato, enfurecer-se,  preocupar-se e afligir-se e mantém-se equilibrado, estável e sereno.');
INSERT INTO frases(frase) VALUES ('A pessoa calma, ao ter aprendido a dominar-se, sabe como adaptar-se aos outros; e os outros, por sua vez respeitam a força espiritual da pessoa, e sentem que podem aprender com a pessoa e confiam nela.');
INSERT INTO frases(frase) VALUES ('Autocontrole é força; Pensamento reto é mestria, calma é poder.');
INSERT INTO frases(frase) VALUES ('Quanto mais tranquila uma pessoa se torna, maior é o seu sucesso, a sua influência, o seu poder para o bem.');
INSERT INTO frases(frase) VALUES ('Quando chegarmos à conclusão de que o pensamento é uma força - uma manifestação de energia - com um poder de atração semelhante a um ímã, começaremos a entender o porquê de muitas coisas que até então nos pareciam obscuras. ');
INSERT INTO frases(frase) VALUES ('Estamos enviando pensamentos de maior ou menor intensidade o tempo todo e estamos colhendo a todo instante, os resultados desses pensamentos.');
INSERT INTO frases(frase) VALUES ('Nossas ondas de pensamento influenciam a nós mesmos e aos outros.  Elas têm um poder de atração - elas atraem para nós os pensamentos dos outros, coisas e circunstâncias  de acordo com o caráter do pensamento que está no topo de nossa mente.');
INSERT INTO frases(frase) VALUES ('Um pensamento forte ou um pensamento continuado por muito tempo nos tornará o centro de atração para as correspondentes ondas de pensamento dos outros. O semelhante atrai o semelhante no mundo do pensamento - como você semeia, assim você deve colher.');
INSERT INTO frases(frase) VALUES ('Quando você parar para pensar, verá que um homem realmente cria seu próprio ambiente, embora culpe os outros por isso. ');
INSERT INTO frases(frase) VALUES ('Passamos pela era da física e  pela era da supremacia intelectual; agora estamos entrando em um campo novo e quase desconhecido, o do poder psíquico. ');
INSERT INTO frases(frase) VALUES ('Quando sua mente está operando em linhas positivas, você se sente forte, dinâmico e você envia um forte pensamento positivo, que afeta os outros e faz com que eles cooperem com você ou para seguir sua liderança, de acordo com a própria nota mental.');
INSERT INTO frases(frase) VALUES ('Quando você toca no extremo negativo sente-se deprimido, passivo e inseguro. Seu efeito sobre os outros é praticamente nulo. Você é liderado, em vez de liderar outros, e seu esforço é totalmente utilizado por pessoas mais positivas.');
INSERT INTO frases(frase) VALUES ('Há mais pessoas no plano negativo do que no positivo, e consequentemente existem mais vibrações de pensamentos negativos em operação em nossa atmosfera mental. ');
INSERT INTO frases(frase) VALUES ('Não permita que ser afetado  pelos pensamentos adversos e negativos das pessoas ao seu redor. Eleve-se às câmaras superiores da sua habitação mental e mantenha-se em um tom forte, acima das vibrações nos planos inferiores do pensamento');
INSERT INTO frases(frase) VALUES ('À medida que os homens avançam na vida, aprendem a se submeter, mais ou menos, a esse Poder dominante que não compreendem, percebendo apenas seus efeitos em si mesmos e no mundo ao seu redor, e o chamam por vários nomes, como Deus, Providência , Destino, Sorte...');
INSERT INTO frases(frase) VALUES ('Você  se vê envolvido no trem da causalidade. Sua vida é composta de causas e efeitos. É uma semeadura e uma colheita.');
INSERT INTO frases(frase) VALUES ('Por mais maravilhosas que sejam as forças da natureza, elas são muito inferiores à combinação de forças inteligentes que compreendem a sua mente e que dominam e dirigem as forças mecânicas cegas da natureza. ');
INSERT INTO frases(frase) VALUES ('Como na ciência comum, existem nesta ciência divina, certos  graus de realização; e uma pessoa  é grande em conhecimento, grande em si mesma e grande em sua influência no mundo, na medida em que ela é grande em autocontrole.');
INSERT INTO frases(frase) VALUES ('Quem entende e domina as forças da natureza externa é o cientista natural; mas quem entende e domina as forças internas da mente é o cientista divino.');
INSERT INTO frases(frase) VALUES ('Cada pessoa  é circunscrita por seus próprios pensamentos, mas você pode gradualmente ampliar seu círculo; você pode ampliar e elevar sua esfera mental. ');
INSERT INTO frases(frase) VALUES ('A pessoa de mente pequena e a pessoa de mente generosa vivem em dois mundos diferentes. Cada uma delas olha para uma ordem diferente de coisas e cada uma recebe segundo a sua visão.');
INSERT INTO frases(frase) VALUES ('O reino dos céus ( consciência desperta) não é tomado pela violência, mas quem está de acordo com seus princípios recebe a senha.');
INSERT INTO frases(frase) VALUES ('Você se move dentro da esfera de seus próprios pensamentos, e essa esfera é seu mundo. ');
INSERT INTO frases(frase) VALUES ('O mundo das coisas é a outra metade do mundo dos pensamentos. O interior informa o exterior.');
INSERT INTO frases(frase) VALUES ('Você não pode derrubar o muro de circunstâncias pelas quais está cercado, mas pode sabiamente se adaptar a ele ou encontrar o caminho para circunstâncias ampliadas, estendendo seu horizonte mental.');
INSERT INTO frases(frase) VALUES ('As coisas seguem pensamentos. Altere seus pensamentos e as coisas receberão um novo ajuste. ');
INSERT INTO frases(frase) VALUES ('Uma mente perturbada dá um reflexo distorcido do mundo.');
INSERT INTO frases(frase) VALUES ('A causa da sua servidão ou da sua libertação está dentro de você.');
INSERT INTO frases(frase) VALUES ('Aquele que reclama de suas circunstâncias ainda não desenvolveu maturidade espiritual, e a necessidade continuará a picá-lo e açoitá-lo até que ele ele o nível de sua própria consciência.');
INSERT INTO frases(frase) VALUES ('Você é,  na natureza das coisas, um ser de hábito, e isso você não pode alterar; mas você  pode alterar seus hábitos. ');
INSERT INTO frases(frase) VALUES ('Hábito é repetição. Você repete os mesmos pensamentos, as mesmas ações, as mesmas experiências repetidamente até que sejam incorporadas ao seu ser; sejam boas ou ruins.');
INSERT INTO frases(frase) VALUES ('Você continuará sendo sujeito a seus próprios hábitos, sejam bons ou ruins - isto é, sujeito a seus próprios pensamentos e ações reiterados e acumulados');
INSERT INTO frases(frase) VALUES ('Nada pode ser superado até que o pensamento de impotência seja arrancado e abolido da sua mente.');
INSERT INTO frases(frase) VALUES ('Uma atitude mental alterada muda o caráter, os hábitos e a vida. Você é seu próprio libertador.');
INSERT INTO frases(frase) VALUES ('. O hábito surge primeiro no pensamento e secundariamente na ação. Transforme o pensamento  ruim em bom, e a ação seguirá imediatamente. ');
INSERT INTO frases(frase) VALUES ('Doença e dor, como pecado e tristeza, são profundos demais para serem removidos por paliativos. Nossas doenças têm uma causa ética profundamente enraizada na mente. ');
INSERT INTO frases(frase) VALUES ('O corpo é a imagem da mente e nele estão traçadas as características visíveis dos pensamentos ocultos. ');
INSERT INTO frases(frase) VALUES ('Você pode reinar sobre sua própria mente.  Vpcê pode ser senhor de si mesmo. Até que você entenda isto, sua vida é insatisfatória e imperfeita. ');
INSERT INTO frases(frase) VALUES ('Seu domínio espiritual é o império das forças mentais das quais sua natureza e resultados são  compostos.');
INSERT INTO frases(frase) VALUES ('O corpo não tem poder causador. A regra do corpo - isto é, do apetite e da paixão - é a disciplina das forças mentais. ');
INSERT INTO frases(frase) VALUES ('Aquele que assumiu a sublime tarefa de vencer a si mesmo, não se resigna a nada que seja mau; ele se submete apenas ao que é bom. Na verdade, ele desconmhece o mau.');
INSERT INTO frases(frase) VALUES ('Todas as coisas são feitas de uma substância viva, que, em seu estado original, permeia, penetra e preenche os interespaços do universo. ');
INSERT INTO frases(frase) VALUES ('Você é um centro de pensamento, capaz de pensamento original; e seu pensamento tem poder sobre seu próprio funcionamento. ');
INSERT INTO frases(frase) VALUES ('O despertar do princípio do poder em você  é a verdadeira conversão. É  a passagem da morte para a vida. ');
INSERT INTO frases(frase) VALUES ('Você  não está condenado aos níveis mais baixos por circunstâncias ou falta de oportunidade. O princípio do poder que há em você é suficiente para todos os desejos de sua alma. ');
INSERT INTO frases(frase) VALUES ('O poder que está em você está nas coisas ao seu redor. E quando você começar a avançar, as coisas se organizarão para entregarem aquilo que você deseja.');
INSERT INTO frases(frase) VALUES ('Quando você desperta sua alma e entra no caminho avançado, você descobre que a natureza, a sociedade, seus semelhantes e todas as coisas trabalham juntas para o seu bem,');
INSERT INTO frases(frase) VALUES ('Existe um Princípio de Poder em você, se você o usar e aplicar de uma certa maneira, poderá superar toda a hereditariedade, dominar todas as circunstâncias e condições e tornar-se uma personalidade grande e poderosa. ');
INSERT INTO frases(frase) VALUES ('Existe uma inteligência cósmica que está em todas as coisas e através de todas as coisas. Esta é a única substância real. A partir disso tudo se cria.');
INSERT INTO frases(frase) VALUES ('A Substância Espiritual Original, Deus, permeia toda a natureza e pensa e conhece todas as coisas.');
INSERT INTO frases(frase) VALUES ('Expulse o orgulho e a vaidade; não pense em tentar dominar os outros ou superá-los.');
INSERT INTO frases(frase) VALUES ('Está tudo bem com o mundo: esse é o grande fato. Não há nada errado com nada; não há nada torcido com ninguém. Você deve ver todos os fatos da vida dessa maneira. ');
INSERT INTO frases(frase) VALUES ('Você não pode ser governado por impulsos físicos; você deve sujeitar seu corpo à mente, mas sua mente deve ser guiada por princípios elevados.');
INSERT INTO frases(frase) VALUES ('Tudo o que é necessário é ser guiado absolutamente, em todas as coisas, por sua luz interior e  sua nova percepção da verdade. ');
INSERT INTO frases(frase) VALUES ('Obedeça à sua alma, tenha perfeita fé em si mesmo. Nunca pense em si mesmo com dúvida ou desconfiança, ou como alguém que comete erros.');
INSERT INTO frases(frase) VALUES ('Qualquer ato, mental ou físico, muitas vezes repetido, se torna um hábito. O objetivo dos exercícios mentais é repetir certos pensamentos repetidamente até que o pensamento desses pensamentos se torne constante e habitual. ');
INSERT INTO frases(frase) VALUES ('Não tente se tornar ótimo repetindo meras sequências de palavras ou fórmulas superficiais: repita repetidamente o PENSAMENTO de seu próprio poder e capacidade até que os fatos externos seja alterados.');
INSERT INTO frases(frase) VALUES ('A grandeza é alcançada apenas pelo pensamento de um grande pensamento.');
INSERT INTO frases(frase) VALUES ('Ninguempode tornar-se grande na personalidade externa até ser grande internamente; e ninguém pode ser ótimo internamente até que PENSE.');
INSERT INTO frases(frase) VALUES ('Pensar é o mais difícil e exaustivo de todos trabalho; e, portanto, muitas pessoas  fogem disso.');
INSERT INTO frases(frase) VALUES ('A busca direta e contínua pelo prazer, na qual a maioria das pessoas passa todo o seu tempo livre, é apenas um esforço para escapar do pensamento.');
INSERT INTO frases(frase) VALUES ('Os homen que pensaram em grandes temas; eles tiveram grandes pensamentos. e eles se tornaram grandes homens.');
INSERT INTO frases(frase) VALUES ('Pensar, não mero conhecimento ou informação, cria personalidade. Pensar é crescer: você não pode pensar sem crescer. ');
INSERT INTO frases(frase) VALUES ('Todo pensamento gera um outro pensamento. Escreva uma idéia e outras seguirão até você escrever uma página. ');
INSERT INTO frases(frase) VALUES ('Você não pode compreender sua própria mente: ela não tem fundo nem limites. Seus primeiros pensamentos podem ser grosseiros: mas, à medida que continuar pensando, você ativará novas células cerebrais e desenvolverá novas faculdades. ');
INSERT INTO frases(frase) VALUES ('Não pode haver grandeza real sem o pensamento original. Tudo o que você faz exteriormente é a expressão e a conclusão de seu pensamento interior. ');
INSERT INTO frases(frase) VALUES ('Nenhuma ação é possível sem pensar. e nenhuma grande ação é possível até que um grande pensamento o preceda. ');
INSERT INTO frases(frase) VALUES ('O meio ambiente é o resultado do pensamento; as coisas se agrupam ou se organizam ao seu redor de acordo com o seu pensamento. ');
INSERT INTO frases(frase) VALUES ('Existe uma idéia ou concepção central de si mesmo pela qual todos os fatos de sua vida são organizados. Mude essa idéia central e você mudará o arranjo de todos os fatos e circunstâncias da sua vida. ');
INSERT INTO frases(frase) VALUES ('Você é o que é porque pensa como pensa; você está onde está porque pensa como pensa.');
INSERT INTO frases(frase) VALUES ('Você é um deus se você pensa como um deus. Se você pensa como um deus, não pode deixar de agir como um deus. Os pensamentos divinos certamente se exteriorizarão em uma vida divina.');
INSERT INTO frases(frase) VALUES ('Não fale sobre sua grandeza: você é realmente, por natureza essencial, não maior do que aqueles que o rodeiam. Você pode ter entrado em um modo de pensar que eles ainda não encontraram, mas eles são perfeitos em seu próprio plano de pensamento e ação.');
INSERT INTO frases(frase) VALUES ('Você cairá na atitude arrogante se perceber as falhas de outras pessoas e compará-las com suas próprias  virtudes e sucessos; e se você cair na atitude arrogante da mente, deixará de ser grande e ficará pequeno. ');
INSERT INTO frases(frase) VALUES ('Pense em si mesmo como um ser perfeito entre os seres perfeitos e conheça todas as pessoas como iguais. não como superiores ou inferiores. ');
INSERT INTO frases(frase) VALUES ('Se sua maneira e atitude em sua própria família são sempre as melhores que você pode pensar, em breve você se tornará aquele em quem todos os outros confiarão. ');
INSERT INTO frases(frase) VALUES ('Você será uma torre de força e um suporte em tempos de angústia. Você será amado e apreciado. ');
INSERT INTO frases(frase) VALUES ('Você não pode ajudar sua família sendo um escravo deles ou fazendo por eles aquilo que, por direito, deveriam fazer por si mesmos.');
INSERT INTO frases(frase) VALUES ('O mundo ideal não é aquele em que muitas pessoas são esperadas por outras pessoas; é um mundo onde todo mundo espera de si mesmo. ');
INSERT INTO frases(frase) VALUES ('Tenha perfeita fé em si mesmo e em sua própria capacidade de lidar com qualquer combinação de circunstâncias que possam surgir. ');
INSERT INTO frases(frase) VALUES ('O que está o impulsionando  está nas coisas e pessoas que você precisa, immpelindo-os em sua direção. Se há alguém em particular que você precisa conhecer, ele será apresentado a você: se houver um livro em particular que você precise ler, ele será colocado em suas mãos na hora certa. ');
INSERT INTO frases(frase) VALUES ('Todos o conhecimento de que você precisa chegará até você de fontes externas e internas. Suas informações e seus talentos sempre serão iguais aos requisitos da ocasião.');
INSERT INTO frases(frase) VALUES ('Não tente fazer grandes coisas até estar pronto para fazê-las da melhor maneira possível.');
INSERT INTO frases(frase) VALUES ('Não tenha pressa para conseguir as grandes coisas. Fazer grandes coisas não o fará ótimo. Mas tornar-se grande certamente o levará a fazer grandes coisas. ');
INSERT INTO frases(frase) VALUES ('Comece a ser ótimo onde você está e nas coisas que faz todos os dias. Não tenha pressa de ser descoberto ou reconhecido como uma grande personalidade.');
INSERT INTO frases(frase) VALUES ('A grandeza é recompensa suficiente para si mesma; a alegria de trazer algo e de saber que você está avançando é a maior de todas as alegrias possíveis para o homem.');
INSERT INTO frases(frase) VALUES ('Se você mantiver o ponto de vista correto do mundo, outros o descobrirão e ficarão impressionados com ele através de suas conversas e práticas diárias. ');
INSERT INTO frases(frase) VALUES ('Se sua identificação com Deus estiver completa, você não precisará explicar o fato a outras pessoas; isso se tornará auto-evidente. ');
INSERT INTO frases(frase) VALUES ('Trate todos com a mesma consideração. Tudo é Deus. Todo homem e mulher é perfeito. Seja como um deus que se dirige a outros deuses. ');
INSERT INTO frases(frase) VALUES ('Você foi treinado em parte, por professores, religião e jornalistas equivocados, para  ver o mundo como um navio naufragado. Essa visão te ensina a considerar o mundo essencialmente ruim e piorando. Isso te rouba a esperança na sociedade, no governo e na humanidade e te dá uma perspectiva decrescente e uma mente contraída.');
INSERT INTO frases(frase) VALUES ('Sua forma de pensamento será modelada principalmente de acordo com o seu ponto de vista do cosmos. Se você vê o mundo como uma coisa perdida e arruinada, verá a si mesmo como parte dele, participando de seus pecados e fraquezas. ');
INSERT INTO frases(frase) VALUES ('Se você vê o mundo declinando no final, não pode se ver avançando. A menos que você pense bem em todas as obras de Deus, você não pode realmente pensar bem em si mesmo, e a menos que você pense bem em si mesmo, nunca poderá se tornar grande.');
INSERT INTO frases(frase) VALUES ('Quando você cria uma forma de pensamento, dificilmente deixará de emocionalizar em sua mente um ambiente correspondente. ');
INSERT INTO frases(frase) VALUES ('Se você se considera incapaz e ineficiente, você vai pensar em si mesmo num ambiente pobre e deficiente.');
INSERT INTO frases(frase) VALUES ('Veja a natureza como uma grande presença viva e avançada, e veja a sociedade humana exatamente da mesma maneira. É tudo um, vindo de uma fonte, e é tudo de bom. ');
INSERT INTO frases(frase) VALUES ('Você nunca se tornará grande até que seus próprios pensamentos o tornem grande. e, portanto, é de primeira importância que você PENSE. ');
INSERT INTO frases(frase) VALUES ('Para se livrar das velhas idéias falsas, você terá que pensar bastante sobre o valor das pessoas - a grandeza e o valor da alma humana. Você deve deixar de olhar para os erros e olhar para os sucessos; deixar de ver as falhas e ver as virtudes.');
INSERT INTO frases(frase) VALUES ('Você não pode mais encarar homens e mulheres como seres perdidos e arruinados que estão descendo ao inferno (inconsciência)  você deve considerá-las almas brilhantes que estão subindo em direção ao céu (consciência).');
INSERT INTO frases(frase) VALUES ('Você se torna grande quando vê que a espiritualidade é mais forte do que qualquer força material e que pensamentos dominam o mundo.');
INSERT INTO frases(frase) VALUES ('O único serviço que você pode prestar a Deus é dar expressão ao que ele está tentando dar ao mundo, através de você. ');
